#!/bin/bash
# This is run manually after the initial provisioning and downloads the rest of the ComyUI nodes

    # "https://github.com/Gourieff/comfyui-reactor-node"
    # "https://github.com/Acly/comfyui-inpaint-nodes"
    # "https://github.com/space-nuko/ComfyUI-OpenPose-Editor"
    # "https://github.com/kijai/ComfyUI-SUPIR"
    # "https://github.com/space-nuko/nui-suite"
    # "https://github.com/adieyal/comfyui-dynamicprompts"
    # "https://github.com/mcmonkeyprojects/sd-dynamic-thresholding"
    # "https://github.com/WASasquatch/was-node-suite-comfyui"
    # "https://github.com/Fannovel16/comfyui_controlnet_aux"
    # "https://github.com/huchenlei/ComfyUI_densediffusion"
    # "https://github.com/cubiq/ComfyUI_InstantID"
    # "https://github.com/heshengtao/comfyui_LLM_party"
    # "https://github.com/huchenlei/ComfyUI_omost"
    # "https://github.com/ssitu/ComfyUI_UltimateSDUpscale"
    # "https://github.com/talesofai/comfyui-browser"
    # "https://github.com/11cafe/comfyui-workspace-manager"
    # "https://github.com/hayden-fr/ComfyUI-Model-Manager"
    # "https://github.com/city96/ComfyUI-GGUF"