COMFY_MODELS_OTHER=(
    "https://civitai.com/api/download/models/963489?type=Model&format=GGUF&size=pruned&fp=fp8"
    "https://civitai.com/api/download/models/1249447?type=Model&format=SafeTensor&size=full&fp=fp8"
    "https://civitai.com/api/download/models/1159932?type=Model&format=SafeTensor&size=full&fp=fp8"
    "https://civitai.com/api/download/models/744068?type=Model&format=SafeTensor&size=full&fp=nf4"
    "https://huggingface.co/comfyanonymous/flux_dev_scaled_fp8_test/resolve/main/flux_dev_fp8_scaled_diffusion_model.safetensors"
    "https://civitai.com/api/download/models/1172273?type=Model&format=SafeTensor&size=pruned&fp=fp32"
    "https://civitai.com/api/download/models/1176578?type=Model&format=SafeTensor&size=pruned&fp=fp32"
    "https://huggingface.co/comfyanonymous/flux_text_encoders/resolve/main/t5xxl_fp8_e4m3fn_scaled.safetensors"
    "https://huggingface.co/Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro/resolve/main/diffusion_pytorch_model.safetensors"
)