name: kustom-kloud:rp.io build w cache, push to GHCR

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0

      - name: Login to GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v4.2.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }} # Unique key for the cache
          restore-keys: |
            ${{ runner.os }}-buildx-  # Restore from partial matches

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.13.0
        with:
          context: .  # Build context is the current directory
          file: ./kustom.Dockerfile
          push: true   # Push the image to the registry
          tags: ghcr.io/${{ github.repository_owner }}/kustom-kloud:rp.io # Replace with your image name
          cache-from: type=local,src=/tmp/.buildx-cache # Use the cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max # Save the new cache

      - name: Move cache (for next run)
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
